#set_property PACKAGE_PIN H9 [get_ports "clk_125_p_i"];
set_property PACKAGE_PIN A17 [get_ports "sw_0[0]"];
set_property PACKAGE_PIN A16 [get_ports "sw_0[1]"];
set_property PACKAGE_PIN B16 [get_ports "sw_0[2]"];
set_property PACKAGE_PIN B15 [get_ports "sw_0[3]"];
set_property PACKAGE_PIN A15 [get_ports "sw_0[4]"];
set_property PACKAGE_PIN A14 [get_ports "sw_0[5]"];
set_property PACKAGE_PIN B14 [get_ports "sw_0[6]"];
set_property PACKAGE_PIN B13 [get_ports "sw_0[7]"];
set_property IOSTANDARD LVCMOS12 [get_ports "sw_0[0]"]
set_property IOSTANDARD LVCMOS12 [get_ports "sw_0[1]"]
set_property IOSTANDARD LVCMOS12 [get_ports "sw_0[2]"]
set_property IOSTANDARD LVCMOS12 [get_ports "sw_0[3]"]
set_property IOSTANDARD LVCMOS12 [get_ports "sw_0[4]"]
set_property IOSTANDARD LVCMOS12 [get_ports "sw_0[5]"]
set_property IOSTANDARD LVCMOS12 [get_ports "sw_0[6]"]
set_property IOSTANDARD LVCMOS12 [get_ports "sw_0[7]"]

set_property PACKAGE_PIN AL11 [get_ports "led_0[0]"]
set_property IOSTANDARD LVCMOS12 [get_ports "led_0[0]"]
set_property PACKAGE_PIN AL13 [get_ports "led_0[1]"]
set_property IOSTANDARD LVCMOS12 [get_ports "led_0[1]"]
set_property PACKAGE_PIN AK13 [get_ports "led_0[2]"]
set_property IOSTANDARD LVCMOS12 [get_ports "led_0[2]"]
set_property PACKAGE_PIN AE15 [get_ports "led_0[3]"]
set_property IOSTANDARD LVCMOS12 [get_ports "led_0[3]"]
set_property PACKAGE_PIN AM8 [get_ports "led_0[4]"]
set_property IOSTANDARD LVCMOS12 [get_ports "led_0[4]"]
set_property PACKAGE_PIN AM9 [get_ports "led_0[5]"]
set_property IOSTANDARD LVCMOS12 [get_ports "led_0[5]"]
set_property PACKAGE_PIN AM10 [get_ports "led_0[6]"]
set_property IOSTANDARD LVCMOS12 [get_ports "led_0[6]"]
set_property PACKAGE_PIN AM11 [get_ports "led_0[7]"]
set_property IOSTANDARD LVCMOS12 [get_ports "led_0[7]"]